# Use an Ubuntu base image
FROM ubuntu:20.04
# Set environment variables to automate tzdata setup
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    tzdata \
    git \
    make \
    g++ \
    gperf \
    binutils \
    python3 \
    python3-serial \
    srecord \
    bc \
    xz-utils \
    flex \
    bison \
    libtool-bin \
    wget \
    unzip \
    libncurses-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-future \
    cmake \
    ninja-build \
    ccache \
    dfu-util \
    sudo \
    npm \
    clang-format \
    apt-transport-https \
    ca-certificates \
    curl \
    libssl-dev \
    apt-utils \
    libusb-1.0-0 &&\
    apt autoremove
RUN mkdir /build
COPY build.sh /usr/bin 
COPY prepare.sh /usr/bin
RUN  chmod +x /usr/bin/build.sh &&\
     chmod +x /usr/bin/prepare.sh &&\
     /usr/bin/prepare.sh
